#
# Makefile for the Free Software Foundations g++ compiler
#
CC=g++
CFLAGS=-g -Wall
all: max stack

max: max.cpp
	$(CC) $(CFLAGS) -o max max.cpp

stack_c1: stack_c1.cpp
	$(CC) $(CFLAGS) -o stack stack.cpp

clean:
	rm max stack
