PROGRAM =       fwrite
OBJS    =       fwrite.o
SRCS    =       $(OBJS:%.o=%.c)
CC      =       gcc
CFLAGS  =       -g -Wall
LDFLAGS =

$(PROGRAM):$(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROGRAM) $(OBJS) $(LDLIBS)
